/*
 * Port_PBcfg.c
 *
 *  Created on: 3 /11 /2018
 *      Author: Ahmed Yusri Mohammed
 *      	To: Graduation Project.
 */

#include <myHWDRIV/AUTOSARCOMP/AUTOSAR_SWS_PortDriver/Port.h>
#include <myHWDRIV/AUTOSARCOMP/AUTOSAR_SWS_PortDriver/Port_MemMap.h>

/*typedef struct{
	Port_PinDirectionType PortPinDirection;
	EcucBooleanParamDef PortPinDirectionChangeable;
	EcucIntegerParamDef PortPinId;
	Port_PinModeType   PortPinInitialMode;
	Pot_PinLevelType   PortPinLevelValue;
	EcucBooleanParamDef PortPinModeChangeable;
}PortPinType;
*/
static PortPinType  A[PIN_NUMBER] = {
		{
			PORT_PIN_IN, I_TRUE,
			PORTA_PIN0,PORT_PIN_MODE_UART,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_OUT, I_TRUE,
			PORTA_PIN1,PORT_PIN_MODE_UART,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTA_PIN2,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTA_PIN3,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTA_PIN4,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTA_PIN5,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTA_PIN6,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTA_PIN7,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTB_PIN0,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTB_PIN1,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTB_PIN2,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTB_PIN3,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTB_PIN4,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTB_PIN5,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTB_PIN6,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTB_PIN7,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTC_PIN0,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTC_PIN1,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTC_PIN2,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTC_PIN3,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTC_PIN4,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTC_PIN5,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTC_PIN6,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTC_PIN7,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTD_PIN0,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTD_PIN1,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTD_PIN2,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTD_PIN3,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTD_PIN4,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTD_PIN5,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTD_PIN6,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTD_PIN7,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTE_PIN0,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTE_PIN1,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTE_PIN2,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTE_PIN3,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTE_PIN4,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTE_PIN5,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTE_PIN6,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTE_PIN7,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTF_PIN0,PORT_PIN_MODE_DIO,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_OUT, I_TRUE,
			PORTF_PIN1,PORT_PIN_MODE_DIO,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_OUT, I_TRUE,
			PORTF_PIN2,PORT_PIN_MODE_DIO,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_OUT, I_TRUE,
			PORTF_PIN3,PORT_PIN_MODE_DIO,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTF_PIN4,PORT_PIN_MODE_DIO,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTF_PIN5,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTF_PIN6,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
		{
			PORT_PIN_IN, I_TRUE,
			PORTF_PIN7,PORT_PIN_NOT_USED,
			PORT_PIN_LEVEL_LOW,I_FALSE
		},
};
Port_ConfigType  PortConfig = {
		A,PIN_NUMBER
};
